{
    'name': 'AI Sale Order Digitalization (OCR)',
    'version': '19.0.8.1',
    'category': 'Extra Tools',
    'summary': """Digitize sale order and populate Odoo records  with the extracted data using    OCR    OpenAI's GPT-3.5,
OpenAI,
GPT-3.5
 Inventory Dashboard,
Sales Dashboard,
Account Dashboard,
 Invoice Dashboard,
Revamp Dashboard,
Best Dashboard,
 Odoo Best Dashboard,
Odoo Apps Dashboard,
 Best Ninja Dashboard,
 Analytic Dashboard,
Pre-Configured Dashboard, 
Create Dashboard,
Beautiful Dashboard,
 Customized Robust Dashboard,
Predefined Dashboard, 
Multiple Dashboards,
Advance Dashboard,
Beautiful Powerful Dashboards,
 Chart Graphs Table View,
All In One Dynamic Dashboard,
 Accounting Stock Dashboard,
 Pie Chart Dashboard,
Modern Dashboard,
Dashboard Studio,
Dashboard Builder,
 Dashboard Designer,
Odoo Studio. 
    
    """,
    'description': """
        This module allows users to digitize sale order, extract relevant information using OCR, and complete Odoo records
         with the extracted data also using artificial intelligence.
         
 Digitize sale order and populate Odoo records  with the extracted data using    OCR    OpenAI's GPT-3.5,
OpenAI,
GPT-3.5
chatgpt
 Inventory Dashboard,
Sales Dashboard,
Account Dashboard,
 Invoice Dashboard,
Revamp Dashboard,
Best Dashboard,
 Odoo Best Dashboard,
Odoo Apps Dashboard,
 Best Ninja Dashboard,
 Analytic Dashboard,
Pre-Configured Dashboard, 
Create Dashboard,
Beautiful Dashboard,
 Customized Robust Dashboard,
Predefined Dashboard, 
Multiple Dashboards,
Advance Dashboard,
Beautiful Powerful Dashboards,
 Chart Graphs Table View,
All In One Dynamic Dashboard,
 Accounting Stock Dashboard,
 Pie Chart Dashboard,
Modern Dashboard,
Dashboard Studio,
Dashboard Builder,
 Dashboard Designer,
Odoo Studio. 
    """,
    'author': "David Montero Crespo",
    'website': 'https://odoonext.com',
    'depends': ['sale', 'purchase', 'sale_management', 'account', 'base', 'mail', 'web'],
    'external_dependencies': {
        'python': ['pytesseract', 'pypdf', 'pdf2image', 'numpy', 'Pillow', 'fuzzywuzzy', 'litellm'],
    },
    'data': [
        'security/ir.model.access.csv',
        'wizard/sale_digitalize.xml',
        'views/sale_order.xml',
        'wizard/purchase_digitalize.xml',
        'views/purchase_order.xml',
        'wizard/invoice_digitalize.xml',
        'views/account_move.xml',
        'views/res_config_settings.xml',
    ],
    'installable': True,
    'application': True,
    'price': 50,
    'auto_install': False,
    'license': 'AGPL-3',
    "images": ["static/ai_completion.gif"],
}
